// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDafMpbcTzZL_NDZxmlOgYciJH0lnKS_3U',
    appId: '1:394497982893:web:3763d861a097f67287e124',
    messagingSenderId: '394497982893',
    projectId: 'browsemovies-bdbb2',
    authDomain: 'browsemovies-bdbb2.firebaseapp.com',
    storageBucket: 'browsemovies-bdbb2.firebasestorage.app',
    measurementId: 'G-N9Q27F7ZKW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGZeHC-VYbb9C-9Uz7kMvFgRKpY5_eR60',
    appId: '1:394497982893:android:07b175b115276a5387e124',
    messagingSenderId: '394497982893',
    projectId: 'browsemovies-bdbb2',
    storageBucket: 'browsemovies-bdbb2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqlbuhj7SdN06isl6eI_JexjXnYrr3cGE',
    appId: '1:394497982893:ios:64ded504be84e25587e124',
    messagingSenderId: '394497982893',
    projectId: 'browsemovies-bdbb2',
    storageBucket: 'browsemovies-bdbb2.firebasestorage.app',
    iosBundleId: 'com.example.browseMovies',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqlbuhj7SdN06isl6eI_JexjXnYrr3cGE',
    appId: '1:394497982893:ios:64ded504be84e25587e124',
    messagingSenderId: '394497982893',
    projectId: 'browsemovies-bdbb2',
    storageBucket: 'browsemovies-bdbb2.firebasestorage.app',
    iosBundleId: 'com.example.browseMovies',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDafMpbcTzZL_NDZxmlOgYciJH0lnKS_3U',
    appId: '1:394497982893:web:5ec2a9d7670c884087e124',
    messagingSenderId: '394497982893',
    projectId: 'browsemovies-bdbb2',
    authDomain: 'browsemovies-bdbb2.firebaseapp.com',
    storageBucket: 'browsemovies-bdbb2.firebasestorage.app',
    measurementId: 'G-576P7W5G1D',
  );
}
